export const datas = [
  {
    id: 1,
    img: require('../imgs/biriyanii.jpg'),
    offer: '30% OFF',
    upto: 'ABOUVE ₹249',
    name: 'Biriyani',
    star: require('../imgs/star-circle.png'),
    rating: '4.2',
    love: require('../imgs/love.png'),
    price: 160,
  },
  {
    id: 2,
    img: require('../imgs/mandhi.jpg'),
    offer: '20% OFF',
    upto: 'UPTO ₹120',
    name: 'Kuzhimandhi',
    star: require('../imgs/star-circle.png'),
    rating: '4.5',
    love: require('../imgs/love.png'),
    price: 210,
  },
  {
    id: 3,
    img: require('../imgs/pizza.jpg'),
    offer: '40% OFF',
    upto: 'ABOVE ₹120',
    name: 'Pizzas',
    star: require('../imgs/star-circle.png'),
    rating: '3.9',
    love: require('../imgs/love.png'),
    price: 140,
  },
  {
    id: 4,
    img: require('../imgs/shawaaii.jpg'),
    offer: '30% OFF',
    upto: 'UPTO ₹120',
    name: 'Shawai',
    star: require('../imgs/star-circle.png'),
    rating: '4.6',
    love: require('../imgs/love.png'),
    price: 360,
  },
  {
    id: 5,
    img: require('../imgs/buregr.jpg'),
    offer: '20% OFF',
    upto: 'ABOVE ₹230',
    name: 'Burger',
    star: require('../imgs/star-circle.png'),
    rating: '4.1',
    love: require('../imgs/love.png'),
    price: 120,
  },
  {
    id: 6,
    img: require('../imgs/shawarma.jpg'),
    offer: '35% OFF',
    upto: 'UPTO ₹60',
    name: 'Shawarma',
    star: require('../imgs/star-circle.png'),
    rating: '3.8',
    love: require('../imgs/love.png'),
    price: 90,
  },
];

export const secnddatas = [
  {
    id: 7,
    img: require('../imgs/pizza-two.jpg'),
    offer: '29% OFF',

    upto: 'ABOVE ₹249',
    name: 'Pizza Ricotta',
    star: require('../imgs/star-circle.png'),
    rating: '3.8',
    brand: 'Pizzas beverages',
    love: require('../imgs/love.png'),
    price: 160,
  },
  {
    id: 8,
    img: require('../imgs/mandhi-two.jpg'),
    offer: '30% OFF',
    upto: 'UPTO ₹149',
    name: 'Nahdi Kuzhimandi',
    star: require('../imgs/star-circle.png'),
    rating: '4.2',
    brand: 'Arabian',
    love: require('../imgs/love.png'),
    price: 230,
  },
  {
    id: 9,
    img: require('../imgs/sandwish.jpg'),
    love: require('../imgs/love.png'),
    offer: '40% OFF',
    upto: 'UPTO ₹49',
    name: 'Chicking Sandwish',
    star: require('../imgs/star-circle.png'),
    rating: '3.8',
    brand: 'ontinental',
    price: 150,
  },
  {
    id: 10,
    img: require('../imgs/broastt.jpg'),
    love: require('../imgs/love.png'),
    offer: '22% OFF',
    upto: 'UPTO ₹259',
    name: 'KFC Broast',
    star: require('../imgs/star-circle.png'),
    rating: '4.8',
    brand: 'KFC',
    price: 460,
  },
];
